name: Build docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap project
      run: make bootstrap
    - name: Build docs
      run: make build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,.husky,@scripts,node_modules,.gitignore,.nvmrc,LICENSE,README.md,Makefile,package-lock.json,package.json'
